### PR TITLE
Add the allofany matching type (#423)

### PR DESCRIPTION
**Pull request by dfandrich**
This is true when all files match any of the patterns.

### CODE REVIEW

**Comment by hstoresin** [comment]
npm run verify -- --tree=merkle-tree.json --hash=08a72001307d26afe079f6582ea5aacbeb7e1a01

**Comment by dfandrich** [comment]
It would be nice to get this into v5. I count 3 open issues that this feature would address, plus my own use case.

**Comment by silverwind** [comment]
I would call this matcher `only`, e.g. it only matches when all specified globs changed exactly with no unmatched files present, like in this table:

| change files | a | a,b | a,b,c |
| ------------ | - | --- | ----- |
| all: [a, b]  | ❌ | ✅   | ✅     |
| only: [a, b] | ❌ | ✅   | ❌     |
| any: [a, b]  | ✅ | ✅   | ✅     |

Is it how this works?

**Comment by dfandrich** [comment]
I don't think that table is accurate, if I'm reading it correctly (where each glob [a, b] matches a single, different file). If I make the globs look like globs for clarity of this interpretation, the table would be:

| changed files |	a |	a,b |	a,b,c |
|--|--|--|--|
| all: [a*, b*] | ❌ |❌ |❌ |
| allofany: [a*, b*] |	✅ |	✅ 	|❌ |
| any: [a*, b*] |	❌ |	✅ |	✅ |

The `all` case can never match anything because a* and b* are disjunct globs, so maybe I misinterpreted your version of the table.

While I'm not married to the name, it should be consistent with the existing operators. `any` and `all` refer to how many paths must match the globs, whereas `only` doesn't fit that pattern since it doesn't say anything about the paths.

**Comment by dfandrich** [comment]
This PR has been superseded by #680.

**Comment by brianluckham** [comment]
dfandrich:allofany

**Comment by dfandrich** [comment]
Note that the semantics of PR #680 turn out not to match this PR's. `AnyGlobMatchesAllFiles` is not the same as `allofany`. It sounds like it should be, but `AnyGlobMatchesAllFiles` has the semantics of `OneGlobMatchesAllFiles` instead.

**Pull request closed without merging**
