### PR TITLE
paginate over all changed files and sync and add "sync-labels" option to enable removing labels

### LINKED ISSUE #14: Remove labels for reverted changes
Reproducing:

1. Change something in a file in some PR.
2. A label will be added to the PR that matches the location of the changed file.
3. Revert the changes on the changed file. (i.e. the PR does not contain changes in such file).
4. The label will still be there on the PR. But it should be removed, since the PR does not affect such file anymore.

### PR DESCRIPTION
**Pull request by kevinphelps**
**Build process**
- run fomatter
  - This might be problem in my environment, but it looks like the code on `master` is not formatted via the `npm run format` command. I see the same changes in other open PRs so I don't think this is isolated to just me.
- generate dist/index.js in a deterministic manner
  - When I run `npm run build` it adds webpack-looking wrapper code to `dist/index.js` every time. It changes the js file even in main.ts is not changed. I changed the build script to `ncc build ./src/main.ts` to compile the TypeScript source directly and it seems to work better.
  - It is possible that this is a problem in my environment, but if it is, I can't seem to figure it out. Like the formatter issue, other open PRs seem to have unrelated changes in their `dist/index.js` as well so this also does not seem isolated to just me.

**Fixes**
- paginate over all changed files
  - This commit is pretty self-explanatory. This is the same source changes as #43, but I have updated `dist/index.js` also.

**Features**
- add "sync-labels" options to enable removing labels
  - When `sync-labels: true` is given, the action will remove any labels when no matching files are modified. This closes #14.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Nice work on the "sync-labels" feature :+1:

Perhaps it is an idea to limit this PR to just that feature to increase the likelihood of it being merged? Pagination is already implemented in #43 and should probably be merged there. Doing the formatting in this PR makes it difficult to review the meaningful changes in this PR (and causes unnecessary merge conflicts).

**Comment by kevinphelps** [comment]
I can rebase this later and see if the formatting is fixed on `master`. I only made those changes in this PR because I could not get a passing build otherwise.

**Comment by ericcornelissen** [comment]
> I can rebase this later and see if the formatting is fixed on master. I only made those changes in this PR because I could not get a passing build otherwise.

Makes sense. The formatting is not yet fixed on master, but it seems you will no longer get a failing build as a result of incorrect formatting.

**Comment by kevinphelps** [comment]
The other issue is that `npm run build` with `master` checked out changes the `dist/index.js` build even though none the TypeScript is changed. I am unsure how to handle this.

**Comment by ericcornelissen** [comment]
> The other issue is that npm run build with master checked out changes the dist/index.js build even though none the TypeScript is changed. I am unsure how to handle this.

I can't help you with that, could be due to a variety of reasons. But I don't think it matters much. Merge conflicts in the dist/index.js file are straightforward to resolve by the maintainers of this action and don't affect reviewing the changes, so I wouldn't worry about it.

**Comment by dakale** [comment]
Thanks for this, and sorry for the huge delay. The maintainership of this action has changed a few times so some older items like this fell off the radar

I merged your changes via https://github.com/actions/labeler/pull/96 to make it a little easier / faster as Im going through and cleaning up a bit

**Pull request closed without merging**
