### PR TITLE
Two minor fixes to the README

### PR DESCRIPTION
**Pull request by ericcornelissen**
- ~~Add syntax highlighting to the "Create Workflow" example YAML~~ See #52
- Update examples to use consistent indentation style (~~I choose to use indentation as much as possible, we can also go for the opposite~~)
- Fixed a typo ("invidual" -> "individual")

### CODE REVIEW

**Comment by dakale** [comment]
Thanks for this! Personally, I prefer unindented (nit picky) but if it is not consistent to that style it should be updated. Typo fix is definitely welcome as is, of course

**Comment by ericcornelissen** [comment]
> Personally, I prefer unindented (nit picky) but if it is not consistent to that style it should be updated.

I will update so that all instances are unindented instead of indented, I have no strong preference other than it being consistent :smile:

**Review by dakale — APPROVED** [review]
LGTM 👍 Thanks!

**Comment by ericcornelissen** [comment]
Should this PR have targetted the `main` branch instead of `master`? Both issues fixed in this PR are still present in the README on `main` :sweat_smile: Should I open a new PR with the exact same changes for that?

**Comment by jsoref** [comment]
@dakale: ping. (Just noticed this divergence while investigating master/main use in https://github.com/actions)

**Comment by pje** [comment]
@ericcornelissen 👋 https://github.com/actions/labeler/pull/146

**Pull request merged**
